package cmd

import (
	"io/ioutil"
	"os"

	"github.com/spf13/cobra"
)

var extractBundleCmdOpts = &extractManifestsCmdOptions{}

var extractBundleCmd = &cobra.Command{
	Use:   "extract-bundle",
	Short: "Extract OLM Bundle",
	Run: func(cmd *cobra.Command, args []string) {
		// generate the tmp dir where to extract the manifests if not spefied from the cmd flags
		if extractManifestsCmdOpts.extractDir == "" {
			tmpDir, err := ioutil.TempDir(os.TempDir(), "bundle-")
			if err != nil {
				handleError(err)
			}

			extractManifestsCmdOpts.extractDir = tmpDir
		}

		if err := DoExtractManifests(cmd.Context(), ocExtractImage("/"), extractBundleCmdOpts); err != nil {
			handleError(err)
		}
	},
}

func init() {
	extractBundleCmd.Flags().StringVarP(&extractBundleCmdOpts.srcImage, "src-image", "i", "", "Source container image. Image must be in bundle format")
	extractBundleCmd.Flags().StringVarP(&extractBundleCmdOpts.destDir, "dest-dir", "d", "", "Destination directory. The bundle from the given source ('src-image') will be copied here.")
	extractBundleCmd.Flags().StringVar(&extractBundleCmdOpts.extractDir, "extract-dir", "", "Destination directory where to extract the manifests, which can be reused as src-dir, by default it wil be autogenerated")
	ewsCmd.AddCommand(extractBundleCmd)
}
