FROM registry.svc.ci.openshift.org/openshift/release:golang-1.13

ENV SHELLCHECK_VERSION=v0.7.0

# Install shellcheck: https://github.com/koalaman/shellcheck
RUN curl -L "https://github.com/koalaman/shellcheck/releases/download/${SHELLCHECK_VERSION}/shellcheck-${SHELLCHECK_VERSION}.linux.x86_64.tar.xz" -o shellcheck.tar.xz \
    && tar -xvf ./shellcheck.tar.xz \
    && mv ./shellcheck*/shellcheck /usr/local/bin \
    && rm -rf ./shellcheck*